spring:
  main:
    banner-mode: off


#  datasource:
#    url: jdbc:mysql://localhost:3306/music_agency
#    username: root
#    password: leon210
#    driver-class-name: com.mysql.cj.jdbc.Driver


#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql


  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.xml
    enabled: true

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

